name: BDD tests

on:
  pull_request:
    branches:
      - "*"
    paths:
      # - apps/web/**
      - .github/workflows/ci-cd-pr-bdd-wallet.yml
  workflow_dispatch:

jobs:
  full-bdd-tests:
    runs-on: ubuntu-latest
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - uses: actions/checkout@v4

      - name: prepare .env for web module
        run: |
          echo "NEXT_PUBLIC_WALLET_APP_API=${{ secrets.NEXT_PUBLIC_WALLET_APP_API }}" > ./apps/web/.env
          echo "NEXT_PUBLIC_ENV=${{ secrets.NEXT_PUBLIC_ENV }}" >> ./apps/web/.env
          echo "NEXT_PUBLIC_API_TIMEOUT=${{ secrets.NEXT_PUBLIC_API_TIMEOUT }}" >> ./apps/web/.env
          echo "NEXT_PUBLIC_API_RETRIES=${{ secrets.NEXT_PUBLIC_API_RETRIES }}" >> ./apps/web/.env
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> ./apps/web/.env

      - name: prepare .env for user module
        run: |
          echo "PRIVATE_KEYCLOAK_REALM=${{ secrets.PRIVATE_KEYCLOAK_REALM }}" > ./apps/user/.env
          echo "PRIVATE_KEYCLOAK_BASE_URL=${{ secrets.PRIVATE_KEYCLOAK_BASE_URL }}" >> ./apps/user/.env
          echo "PRIVATE_KEYCLOAK_CLIENT_SECRET=${{ secrets.PRIVATE_KEYCLOAK_CLIENT_SECRET }}" >> ./apps/user/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./apps/user/.env
          echo "PRIVATE_KEYCLOAK_CLIENT_ID=${{ secrets.PRIVATE_KEYCLOAK_CLIENT_ID }}" >> ./apps/user/.env
          echo "PRIVATE_WALLET_API_KEY=${{ secrets.PRIVATE_WALLET_API_KEY }}" >> ./apps/user/.env
          echo "CORS_ORIGINS_DEV=${{ secrets.CORS_ORIGINS_DEV }}" >> ./apps/user/.env
          echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}" >> ./apps/user/.env

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install the latest Chrome binary
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install google-chrome-stable

      - name: Add a Chrome driver
        run: CHROMEDRIVER_VERSION=LATEST yarn add chromedriver

      - name: Start user service in the background
        run: |
          yarn user:dev &
          yarn web:dev &

      - name: Run full bdd test
        uses: cypress-io/github-action@v6
        with:
          command: yarn bdd:test:report
